### ISSUE TITLE
Observações sobre o exercício

### ISSUE THREAD

**Issue by PauloJeff** [aliffeKauling/exercicio_C-A#1]
**Program.cs**

1. Poderia ter migrado a lógica dos seus exercícios pra dentro das classes auxiliares de cada exercício. Tome muito cuidado com estruturas switch  case, elas podem dificultar a legibilidade de seu código.
2. Poderia ter migrado também, as funções de input de dentro do Program pras suas classes auxiliares, para dar uma limpada na class Program.

**Animal.cs**

1. Faltou uma validação ali referente ao nome do animal, se o cliente colocar uma letra maiúscula que seja, seu código quebra.
2. Classe está bem construída.

**IMC**

1. Gostei que tu foi além, nos graus de obesidade.

**Volume**

1. Poderia ter usado a função de exponencial e a constante de PI presente no C#.

**Observações gerais**
Num geral seu código está bom, gostei da lógica em alguns pontos e da ideia de usar classes auxiliares para cada exercício.
Só poderia ter utilizado elas de uma forma melhor, para limpar o código do Program.
Mas gostei do resultado, está de parabéns!

**Comment by aliffeKauling** [comment]
Aplicadas as melhorias propostas.
*Obs: Apenas não mexi na classe e lógica de Animal.
